Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceAfterNot:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/LineLength:
  Max: 110
Metrics/MethodLength:
  Max: 30
Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: 'inline'
Style/BlockDelimiters:
  EnforcedStyle: 'semantic'
Style/ConditionalAssignment:
  EnforcedStyle: 'assign_inside_condition'
  IncludeTernaryExpressions: false
Style/Documentation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/Next:
  Enabled: false
Style/ParenthesesAroundCondition:
  AllowInMultilineConditions: true
  AllowSafeAssignment: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'consistent_comma'
